### ISSUE TITLE
RFC: Add API Objects to define Darkroom instances in Kubernetes

### ISSUE THREAD

**Issue by ajatprabha** [gojekfarm/darkroom-operator#1]
##### What would you like to be added

Define API objects[[CRDs - Custom Resource Definitions](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/)] to persist information in Kubernetes' `etcd` store and use them in the operator to reconcile Darkroom as defined in the CRD.

```yaml
apiVersion: deployments.gojek.io/v1alpha1
kind: Darkroom
metadata:
  name: darkroom-web
spec:
  source:
    type: WebFolder
    baseUrl: https://example.com/assets
  domains:
    - darkroom-web.named-example.com
  version: 0.1.0

---

apiVersion: deployments.gojek.io/v1alpha1
kind: Darkroom
metadata:
  name: darkroom-aws
spec:
  source:
    type: S3
  bucket:
    name: "myAwesomeBucket"
    region: "region"
    accessKey: "randomAccessKey"
    secretKey: "superSecret"
  pathPrefix: "/prefixPath/to/folder"
  domains:
    - darkroom-aws.named-example.com
  version: latest
```

##### Why is this needed

This change will be the first step towards creating an operator that manages a cluster of Darkroom instances and its configuration.

##### Comments

This is an initial implementation where almost everything is inside `Darkroom` CRD. In next iteration/improvement we can have separate CRDs to manage `Source`/`Hystrix` configs in their own CRD and reference those in `Darkroom`.
